"""Recording prompts for dataset capture. Each yields a 3-10s utterance so takes
are directly training-ready (GPT-SoVITS wants 3-10s segments — no VAD needed).

Mix: Harvard sentences (public domain, phonetically balanced), questions and
exclamations for pitch range, numbers/dates, and short conversational passages.
"""

# (category, text)
SCRIPTS: list[tuple[str, str]] = [
    # ---- neutral: Harvard sentences ----
    ("neutral", "The birch canoe slid on the smooth planks."),
    ("neutral", "Glue the sheet to the dark blue background."),
    ("neutral", "It's easy to tell the depth of a well."),
    ("neutral", "These days a chicken leg is a rare dish."),
    ("neutral", "Rice is often served in round bowls."),
    ("neutral", "The juice of lemons makes fine punch."),
    ("neutral", "The box was thrown beside the parked truck."),
    ("neutral", "Four hours of steady work faced us."),
    ("neutral", "A large size in stockings is hard to sell."),
    ("neutral", "The boy was there when the sun rose."),
    ("neutral", "A rod is used to catch pink salmon."),
    ("neutral", "The source of the huge river is the clear spring."),
    ("neutral", "Kick the ball straight and follow through."),
    ("neutral", "Help the woman get back to her feet."),
    ("neutral", "A pot of tea helps to pass the evening."),
    ("neutral", "Smoky fires lack flame and heat."),
    ("neutral", "The soft cushion broke the man's fall."),
    ("neutral", "The salt breeze came across from the sea."),
    ("neutral", "The girl at the booth sold fifty bonds."),
    ("neutral", "The small pup gnawed a hole in the sock."),
    ("neutral", "The fish twisted and turned on the bent hook."),
    ("neutral", "Press the pants and sew a button on the vest."),
    ("neutral", "The swan dive was far short of perfect."),
    ("neutral", "The beauty of the view stunned the young boy."),
    ("neutral", "Two blue fish swam in the tank."),
    ("neutral", "Her purse was full of useless trash."),
    ("neutral", "The colt reared and threw the tall rider."),
    ("neutral", "It snowed, rained, and hailed the same morning."),
    ("neutral", "Read verse out loud for pleasure."),
    ("neutral", "Hoist the load to your left shoulder."),
    ("neutral", "Take the winding path to reach the lake."),
    ("neutral", "Note closely the size of the gas tank."),
    ("neutral", "Wipe the grease off his dirty face."),
    ("neutral", "Mend the coat before you go out."),
    ("neutral", "The wrist was badly strained and hung limp."),
    ("neutral", "The stray cat gave birth to kittens."),
    ("neutral", "The young girl gave no clear response."),
    ("neutral", "The meal was cooked before the bell rang."),
    ("neutral", "What joy there is in living."),
    ("neutral", "A king ruled the state in the early days."),
    ("neutral", "The ship was torn apart on the sharp reef."),
    ("neutral", "Sickness kept him home the third week."),
    ("neutral", "The wide road shimmered in the hot sun."),
    ("neutral", "The lazy cow lay in the cool grass."),
    ("neutral", "Lift the square stone over the fence."),
    ("neutral", "The rope will bind the seven books at once."),
    ("neutral", "Hop over the fence and plunge in."),
    ("neutral", "The friendly gang left the drug store."),
    ("neutral", "Mesh wire keeps chicks inside."),
    ("neutral", "The frosty air passed through the coat."),

    # ---- questions: rising intonation, pitch variety ----
    ("question", "Are you sure this is the right way to the station?"),
    ("question", "What time does the next train actually leave?"),
    ("question", "Could you pass me that book on the top shelf?"),
    ("question", "Why would anyone turn down an offer like that?"),
    ("question", "Have you ever seen the northern lights in person?"),
    ("question", "Do you want the long version or the short one?"),
    ("question", "Who left the window open during the storm?"),
    ("question", "How much longer do we have to wait out here?"),
    ("question", "Is there any coffee left in the pot, or did you finish it?"),
    ("question", "Where exactly did you say you parked the car?"),

    # ---- expressive: energy, emphasis, emotion ----
    ("expressive", "That was absolutely incredible — I can't believe we pulled it off!"),
    ("expressive", "No way. There is no way that just happened."),
    ("expressive", "Watch out! The path gets really slippery right there."),
    ("expressive", "Honestly, this might be the best meal I've ever had."),
    ("expressive", "I'm so tired I could sleep for an entire week."),
    ("expressive", "Wait, wait, wait — go back to the part about the treasure."),
    ("expressive", "Oh come on, you've got to be kidding me right now."),
    ("expressive", "Yes! Finally! I've been waiting months for this news."),
    ("expressive", "Shh — keep your voice down, they're still sleeping."),
    ("expressive", "Well, that didn't go the way I expected at all."),
    ("expressive", "It's fine. Everything is fine. I am completely calm."),
    ("expressive", "You should have seen the look on his face — priceless."),

    # ---- numbers, dates, spelling ----
    ("numbers", "The meeting moved from March third to April twenty-first."),
    ("numbers", "Call me back at five five five, zero one nine eight."),
    ("numbers", "It costs forty-seven dollars and ninety-nine cents with tax."),
    ("numbers", "The flight departs at six forty-five in the morning."),
    ("numbers", "Nineteen eighty-four was a strange year for everyone."),
    ("numbers", "Mix two cups of flour with three quarters of a cup of sugar."),
    ("numbers", "The password is capital B, seven, lowercase q, two, nine."),
    ("numbers", "Roughly sixty percent of the budget went to research."),

    # ---- passages: short conversational two-liners ----
    ("passage", "I checked the forecast this morning. Rain all weekend, so the hike is off."),
    ("passage", "She opened the letter slowly. Inside was a single photograph of the old house."),
    ("passage", "The trick is patience. Let the dough rest overnight and it practically bakes itself."),
    ("passage", "He wasn't always this quiet. Something changed after that summer by the coast."),
    ("passage", "First we lost the map. Then the flashlight died, and the rain started."),
    ("passage", "Look, I get why you're upset. But walking away now would be a mistake."),
    ("passage", "The market opens at dawn. If you want the good tomatoes, you arrive before seven."),
    ("passage", "Nobody remembered whose idea it was. By midnight, it didn't matter anymore."),
    ("passage", "Keep your eyes on the horizon. The seasickness fades once you stop fighting it."),
    ("passage", "The library smelled of dust and rain. She found the book exactly where she'd left it, ten years ago."),
]
